# Generated by Django 5.0.3 on 2024-04-18 01:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(default=datetime.date.today)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('fechaCreacion', models.DateField(default=datetime.date.today)),
                ('fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fuente')),
                ('autores', models.ManyToManyField(to='main.usuario')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
