# Generated by Django 5.0.3 on 2024-04-05 21:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
                ('fechaCreacion', models.DateField(default=datetime.date.today)),
                ('tipo', models.IntegerField(null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AlterField(
            model_name='nota',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='nota',
            name='fechaCreacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nota',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fuente'),
        ),
        migrations.AddField(
            model_name='nota',
            name='autores',
            field=models.ManyToManyField(to='main.usuario'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
