# Generated by Django 5.0.3 on 2024-04-18 03:03

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fuente_url_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateField(default=datetime.date.today, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
