# Generated by Django 5.0.3 on 2024-04-18 03:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usuario_correo_alter_usuario_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(default=2, verbose_name=django.contrib.auth.models.User),
        ),
    ]
