# Generated by Django 5.0.3 on 2024-04-18 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usuario_options_remove_usuario_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AlterField(
            model_name='nota',
            name='autores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
