# Generated by Django 5.0.3 on 2024-04-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usuario_options_alter_nota_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='url',
        ),
    ]
